<a href="https://colab.research.google.com/github/vgaurav3011/EIP-3.0-/blob/master/EIP_Week_2_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 2A
---
# Backpropagation Step by Step

![1](https://lh3.googleusercontent.com/IYnRhAcGpbHh_LnSDWsjVy2gRJa_MbJRT4KR_GVsNPLmJaM8V7lRZftGm4_rdODc5Dy05g=s144)

If you are building your own neural network, you will definitely need to understand how to train it. Backpropagation is a commonly used technique for training neural network. There are many resources explaining the technique, but this post will explain backpropagation with concrete example in a very detailed colorful steps.

## Overview
In this post, we will build a neural network with three layers:

* **Input layer with two inputs neurons**

* **One hidden layer with two neurons**

* **Output layer with a single neuron**

![2](https://lh3.googleusercontent.com/t1wVtiNCe8SwLkTkMlO2XBeaRrWOCZL_UDBSb3FvKS6DP_nBXV6tS5OMp3MO6EoJaGdyTA=s152)

## Weights, weights, weights
Neural network training is about finding weights that minimize prediction error. We usually start our training with a set of randomly generated weights.Then, backpropagation is used to update the weights in an attempt to correctly map arbitrary inputs to outputs.

Our initial weights will be as following: 
* **`w1 = 0.70`**,
* **`w2 = 0.71`**,
* **`w3 = 0.92`**,
* **`w4 = 0.15`**,
* **`w5 = 0.58`**,
* **`w6 = 0.61`**
## Dataset
Our dataset has one sample with two inputs and one output.

![3](https://lh3.googleusercontent.com/sPVW5Wgk0FoidpbUCl2_yBxEHqyFJmD9xyRUSrJoRpd6s-2TPobS2ynF8wwIBudecVGcwDM=s170)

Our single sample is as following inputs=[2, 3] and output=[1].

![4](https://lh3.googleusercontent.com/9N3orxW0AB7Z2aTp-OGd07BkJ9lH74BhFNfpTdiQ7ChiLxRsjZxFrhIkVlbD8ImT4KtXzIM=s170)

## Forward Pass
We will use given weights and inputs to predict the output. Inputs are multiplied by weights; the results are then passed forward to next layer.

## Calculating Error
The error calculated by mean square method is given as 0.0708

## Reducing Error
Our main goal of the training is to reduce the error or the difference between prediction and actual output. Since actual output is constant, “not changing”, the only way to reduce the error is to change prediction value. The question now is, how to change prediction value?

By decomposing prediction into its basic elements we can find that weights are the variable elements affecting prediction value. In other words, in order to change prediction value, we need to experiment with weight values. I have assigned as random weight generator for the program and it gives a good accuracy.

![5](https://lh3.googleusercontent.com/KNnpNrGjAhvNNZcDvn_Jo6JoC6ey-v4LuHHuYjglFz5h4BBwx1r-zL9IPSh5FgrTMj2Ymg=s170)

The problem is to update the weights to minimize error.
The answer is Backpropagation!

## Backpropagation
Backpropagation, short for “backward propagation of errors”, is a mechanism used to update the weights using gradient descent. It calculates the gradient of the error function with respect to the neural network’s weights. The calculation proceeds backwards through the network.

Gradient descent is an iterative optimization algorithm for finding the minimum of a function; in our case we want to minimize th error function. To find a local minimum of a function using gradient descent, one takes steps proportional to the negative of the gradient of the function at the current point.

![6](https://lh3.googleusercontent.com/Ym3TielatgesBc__UvlHTNhzqjg7bjB10LcXoXKdBDdUKLu9BRKdNbj-54Z10tP_Bcl1_g=s132)

For example, to update w6, we take the current w6 and subtract the partial derivative of error function with respect to w6. Optionally, we multiply the derivative of the error function by a selected number to make sure that the new updated weight is minimizing the error function; this number is called learning rate.

![7](https://lh3.googleusercontent.com/VeMwq8oAzTUHlJim0t34sj6czafm645L4vsV-jSaOy1jbwhHQxAKjTsN_fGIy7lUDnM5=s170)

The derivation of the error function is evaluated by applying the chain rule as following

![8](https://lh3.googleusercontent.com/a68NxgmSckPQQ4ptXVsvLMWLWvUsGKTHh9Ag29g_oEdrj-YVJ2Alo4a3NujTnx9wBhJD1A=s170)

So to update w6 we can apply the following formula

![9](https://lh3.googleusercontent.com/XvIxPY_DrPV6Se5tIKXBNyefna8Y_I9y_a_gLHk2dwmZhOOwfVKkcE3eZohn4ioCD5D-0g=s170)

Similarly, we can derive the update formula for w5 and any other weights existing between the output and the hidden layer.

![10](https://lh3.googleusercontent.com/okcxZ1FUKaIslnMexCEt5XvTAfQj6h5IsCTS_IdiFqmFykh6-_qTyVv5s4Nj3y7FTfUTug=s170)

However, when moving backward to update w1, w2, w3 and w4 existing between input and hidden layer, the partial derivative for the error function with respect to w1, for example, will be as following.

![11](https://lh3.googleusercontent.com/t4XMRnXgUCMNaPrDovhZH2o88ICY8TQtH0YbdDKKN4eWtsxAecjIfZ09VkjKa8hJkzOA1T4=s170)

We can find the update formula for the remaining weights w2, w3 and w4 in the same way.

In summary, the update formulas for all weights will be as following:

![12](https://lh3.googleusercontent.com/Y3cw7TPEhTSkmGBREB8BORoQAia38dFVcmlwzD7SzmTvmRVY6tq4W6-g8iwuxyxw4uB_qg=s153)

We can rewrite the update formulas in matrices as following

![13](https://lh3.googleusercontent.com/FYPKbZB246-KhETXv8tk8MIt_yDoRuaSBd_-XRzvWKAPMRSwhTyMfZgAEKlT4s4OCB5VJA=s170)


## Backward Pass
Using derived formulas we can find the new weights.

**Learning rate**: is a hyperparameter which means that we need to manually guess its value.
* `a = 0.05`*

Now, using the new weights we will repeat the forward passed

We can notice that the prediction 0.26 is a little bit closer to actual output than the previously predicted one 0.191. We can repeat the same process of backward and forward pass until error is close or equal to zero.
In a random state implememntation, we have the following code given and executed with proper woring displays as shown in the outputs of the follwoing code


In [0]:
import numpy as np
X = np.asarray([[0.21,0.22],[0.11,0.38]])
y = np.asarray([[0.4],[0.5]])
wh = np.random.randn(2,2)
bh = np.random.rand(1,2)
wout = np.random.randn(2,1)
bout = np.random.randn(1)
print('wh')
print(wh)
print('bh')
print(bh)
print('wout')
print(wout)
print('bout')
print(bout)

hidden_layer_input = np.dot(X,wh)+bh
print('hidden_layer_input')
print(hidden_layer_input)
def sigmoid(X):
    return (1 / (1 + np.exp(- X)))

hiddenlayer_activations = sigmoid(hidden_layer_input)
print('hiddenlayer_activations')
print(hiddenlayer_activations)
output_layer_input = np.dot(hiddenlayer_activations, wout )
output = sigmoid(output_layer_input)
print('output')
print(output)



wh
[[-0.4026817  -0.82776876]
 [ 0.15914167 -0.64086958]]
bh
[[0.388173   0.52727792]]
wout
[[ 1.18827715]
 [-1.65376736]]
bout
[-0.85562062]
hidden_layer_input
[[0.33862101 0.21245517]
 [0.40435185 0.19269292]]
hiddenlayer_activations
[[0.58385551 0.55291491]
 [0.59973279 0.54802472]]
output
[[0.44506999]
 [0.45173658]]


In [0]:
E = y-output
print('E')
print(E)
def dsigmoid(y):
    return y * (1.0 - y)
Slope_output_layer= dsigmoid(output)
Slope_hidden_layer = dsigmoid(hiddenlayer_activations)
lr = 0.05
d_output = E * Slope_output_layer * lr
print('d_output')
print(d_output)

Error_at_hidden_layer = np.dot(d_output, np.transpose(wout))
print('Error_at_hidden_layer')
print(Error_at_hidden_layer)

d_hiddenlayer = Error_at_hidden_layer * Slope_hidden_layer
print('d_hiddenlayer')
print(d_hiddenlayer)

wout = wout + np.dot(np.transpose(hiddenlayer_activations), d_output) * lr
wh = wh + np.dot(np.transpose(X),d_hiddenlayer) * lr
print('wout')
print(wout)
print('wh')
print(wh)

bh = bh + np.sum(d_hiddenlayer, axis=0) * lr
bout = bout + np.sum(d_output, axis=0) * lr

print('bh')
print(bh)
print('bout')
print(bout)

E
[[-0.04506999]
 [ 0.04826342]]
d_output
[[-0.00055658]
 [ 0.00059767]]
Error_at_hidden_layer
[[-0.00066137  0.00092045]
 [ 0.0007102  -0.00098841]]
d_hiddenlayer
[[-0.00016069  0.00022753]
 [ 0.00017049 -0.00024482]]
wout
[[ 1.18827882]
 [-1.65376637]]
wh
[[-0.40268245 -0.82776771]
 [ 0.15914314 -0.64087173]]
bh
[[0.38817349 0.52727706]]
bout
[-0.85561857]
